version: '3.7'

services:
  sql2sheets:
    image: rbritta/sql2sheets:1.0.0
    container_name: sql2sheets
    ports:
      - 8080:8080
    environment:
      TZ: America/Sao_Paulo
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    restart: unless-stopped

